deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    copy_files: /abcd ~/code
    squash_pr_comments: true
  branch:
    vm_size: 1
    vm_storage_gb: 13
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
  nodocker:
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
    pipelines:
      - default:
          build_steps:
            - apt-get install -y git
            - ls -la
            - cat ./pipeline-start.sh
          scripts:
            - echo true
